version: "3.9"
services:

  balance-api:
    restart: on-failure
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080


  db:
    restart: on-failure
    image: postgres:alpine

    container_name: postgres-db

    environment:
       ARGS: -env
       
       POSTGRES_PORT: ${DB_PORT}
       POSTGRES_USER: ${DB_USERNAME}
       POSTGRES_PASSWORD: ${DB_PASSWORD}

       POSTGRES_DB: ${DB_NAME}
       POSTGRES_HOST: ${DB_HOST}

    ports:
      - 5432

